fs:
  image: tianon/true
  volumes:
    - ./mysql-datadir:/var/lib/mysql
    - ./mysql-shr:/shr
    - ./mysql-autoload:/docker-entrypoint-initdb.d:ro
    - ./mysql-conf.d:/etc/mysql/conf.d
    - ./srv/releases:/opt/jboss/wildfly/releases
    - ./srv/logs:/opt/jboss/wildfly/standalone/logs
    - ./srv/deployments:/opt/jboss/wildfly/standalone/deployments
    - ./srv/media:/opt/data/media

db:
  image: mysql:5.5
  environment:
    - TZ=Europe/Stockholm
    - MYSQL_ROOT_PASSWORD=supersecret
    - MYSQL_DATABASE=media
    - MYSQL_USER=mediaserver
    - MYSQL_PASSWORD=mediaserver
  volumes_from:
    - fs

app:
  build: wildfly-custom
  environment:
   - VIRTUAL_HOST=api.nrm.se
  volumes_from:
    - fs
  links:
    - db

proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  links:
    - app
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
