fs_db.media:
  image: tianon/true
  volumes:
    - ./mysql_media-datadir:/var/lib/mysql:z
    - ./mysql_media-shr:/shr:z
    - ./mysql_media-autoload:/docker-entrypoint-initdb.d:ro
    - ./mysql_media-conf.d:/etc/mysql/conf.d:z

fs_ws:
  image: tianon/true
  volumes:
    - ./nginx-html:/usr/share/nginx/html:z
    - ./nginx-conf:/etc/nginx/conf.d:z
    - ./nginx-certs:/etc/nginx/ssl:z
    - ./nginx-logs:/etc/nginx/logs:z

fs_as:
  image: tianon/true
  volumes:
    - ./srv/releases:/opt/jboss/wildfly/releases
    - ./srv/log:/opt/jboss/wildfly/standalone/logs
    - ./srv/deployments:/opt/jboss/wildfly/standalone/deployments

db.media:
  image: mysql:5.5
  environment:
    - TZ=Europe/Stockholm
    - MYSQL_ROOT_PASSWORD=supersecret
    - MYSQL_DATABASE=media
    - MYSQL_USER=mediaserver
    - MYSQL_PASSWORD=mediaserver
  ports:
   - "13306:3306"
  volumes_from:
    - fs_db.media

app:
  build: ./wildfly-custom
  ports:
   - "18080:8080"
   - "19990:9990"
  volumes_from:
    - fs_as
  links:
    - db.media:dbmedia

web:
  image: nginx
  environment:
   - VIRTUAL_HOST=beta-media.dina-web.net
   - VIRTUAL_PORT=443
   - VIRTUAL_PROTO=https
   - CERT_NAME=shared
  volumes_from:
    - fs_ws
  links:
    - app